spring.application.name=CachingApp

server.port=8082
spring.datasource.url = jdbc:mysql://localhost:3306/caching
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# needs to enable the caching we can create the seprate config class for it or we can simply
# used it on the Main method class

