spring.application.name=inventry-Service

server.servlet.context-path=/api/v1
server.port=9010

#Db Configuration 
 spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
 spring.datasource.username=postgres
 spring.datasource.password=root
 spring.jpa.hibernate.ddl-auto=create-drop
 
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.formate_sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql