spring.application.name=Testing-App
# Database Configuration 

spring.datasource.url=jdbc:postgressql://localhost:5432/demo4
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true